### ISSUE TITLE
Housing for sensors, switches (top and bottom), and the ESPCAM board

### ISSUE THREAD

**Issue by RolandWijnen** [hms-11/CoopCommand#11]
Hi, 

I've made good progress with the assembly of the main board as mentioned in my other post. I have a couple of questions related to bringing everything together;

1.  How are your sensor boards (SkyEye, DHT22) setup? Did you put them in a standard enclosure? 

![IMG_20211219_171322](https://user-images.githubusercontent.com/24925747/146690480-acd0c59c-9aa2-4346-b5f6-5642821350f8.jpg)

2. What switches did you use for detecting whether the door is at top and bottom? I did not see these components in your BOMs. Can you send me a picture of how these are mounted on your chicken coop?

3. How should the ESPCAM board be assembled? On this photo (https://hackster.imgix.net/uploads/attachments/1290503/czvqlbh_giJi0WB0Rl.jpeg?auto=compress%2Cformat&w=740&h=555&fit=max) I see that you've mounted the components on the backside of the PCB. Is that the right way? Or should the components be mounted to the side printed with text and symbols. See the photo below. 

![IMG_20211219_170211](https://user-images.githubusercontent.com/24925747/146690527-17c599b3-d347-4753-a596-986dca7fcb81.jpg)

Thanks in advance for your support!

**Comment by RolandWijnen** [comment]
I think I've solved Question 3 already. The ESP board needs to be on the other side so that the pins correspond with the board layout. I guess the other components, except the connector, also need to be on the other side so that everything fits in the housing. Is that correct?

**Comment by hms-11** [comment]
Yeah, that version of the ESP board needs to be mounted as described. An unfortunate footprint error in my pcb design software means everything but the connector needs to be mounted on the back side of the board. 

I made some small 3D printed enclosures for the sensor boards. The photocell one I also coated with a waterproof coating (nail polish works fine) before putting it in the enclosure. I just uploaded the 3D files for those pieces to the repository. 

I used Normally Closed (NC) magnetic reed switches for the door. The best way I found to buy them was as "magnetic security door sensors" as they are called here. Then you get a rugged housing and easy mounting as well. I went with these switches because they can't gum up or otherwise blocked/plugged. 
Here is an example of what I used:
https://www.amazon.ca/Uxcell-a14060400ux0169-Magnetic-Door-Switch/dp/B00PZMG980/ref=sr_1_9?keywords=magnetic+door+sensor&qid=1640054668&sprefix=magnetic+door+sen%2Caps%2C130&sr=8-9

**Comment by RolandWijnen** [comment]
Thanks for the quick reply and info! I'll probably put the sensors in a standard enclosure. I've also ordered the reed switches. 

I've already been playing around with Blynk and created the interface based on your notes. I also setup my own local Blynk server so that I don't depend on the cloud :-)
